[project]
name = "comfyui-fast-grow-mask"
description = "CPU-optimized, pixel-compatible Grow Mask With Blur fork for ComfyUI."
version = "0.1.3"
license = {file = "LICENSE"}
dependencies = ["pillow>=10.3.0", "color-matcher", "matplotlib"]

[project.urls]
Repository = "https://github.com/aoiro0X0/ComfyUI-Fast-GrowMask"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "aoiro0X0"
DisplayName = "ComfyUI Fast Grow Mask"
Icon = "https://avatars.githubusercontent.com/u/40791699"
